import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav><ul>
            <a class="nav nav_cnt" href="index.html"><li>Top</li></a>
            <a class="nav" href="soft.html"><li>Software</li></a>
            <a class="nav" href="prog.html"><li>Programming</li></a>
            <a class="nav" href="others.html"><li>Others</li></a>
            <a class="nav" href="prof.html"><li>Profile</li></a>
        </ul></nav>

        <div class="mainBar">
            <img src="img/head.png">
        </div>
        <div class="bottomBar">
        </div>

        <h1 class="contents">Contents</h1>
        <div>
            <section class="elements"><a href="soft.html">
                <h1>
                    <div class="soft"></div><nobr>フリーソフト</nobr>
                </h1>
                <img src="img/soft.png" alt="フリーソフト">
                <p>PC向けフリーソフトウェア。<br>日々の作業の効率化を。</p>
            </a></section>
            <section class="elements"><a href="prog.html">
                <h1>
                    <div class="prog"></div><nobr>競プロ解説</nobr>
                </h1>
                <img src="img/prog.png" alt="フリーソフト">
                <p>競技プログラミングサイト<br>Atcoderの問題の解説。</p>
            </section></a>
            <section class="elements"><a href="others.html">
                <h1>
                    <div class="others"></div><nobr>その他記事</nobr>
                </h1>
                <img src="img/others.png" alt="その他">
                <p>その他の雑他なコンテンツ。<br>旅行記・日記等を放置。</p>
            </a></section>
        </div>
        <h1 class="contents">Profile</h1>
        <iframe class="prof" src="./prof.html"></iframe>

        <iframe class="foot" src="./foot.html"></iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
